// <auto-generated />
using System;
using HejCamping.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HejCamping.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HejCamping.Domain.Entities.Booking", b =>
                {
                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CabinNr")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalPrice")
                        .HasColumnType("real");

                    b.HasKey("OrderNumber");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HejCamping.Domain.Entities.Review", b =>
                {
                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
<<<<<<< HEAD
                        .IsRequired()
                        .HasColumnType("TEXT");
=======
                        .HasColumnType("nvarchar(max)");
>>>>>>> a868fb50ef6a55ba74280cfb24c752d5943c4951

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewText")
<<<<<<< HEAD
                        .IsRequired()
                        .HasColumnType("TEXT");
=======
                        .HasColumnType("nvarchar(max)");
>>>>>>> a868fb50ef6a55ba74280cfb24c752d5943c4951

                    b.HasKey("OrderNumber");

                    b.ToTable("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
