name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - CAM-35-Try-running-app-in-Azure-Container-Apps  # Specify the branch to trigger the workflow
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        
      # Login to Azure CLI using service principal credentials
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Log in to Azure Container Registry
      - name: 'Log in to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      # Build and push the Docker image to Azure Container Registry
      - name: Build and push Docker image to ACR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            hejcampingregistry.azurecr.io/hej-camping-app2:latest
            hejcampingregistry.azurecr.io/hej-camping-app2:${{ github.sha }}
          file: ./Dockerfile
          
      - name: 'Deploy to Azure Container Apps'
        run: |
          az containerapp update --name hej-camping-app2 \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/hej-camping-app2:latest
            --image-pull-policy Always
            
      - name: 'Force Update Azure Container App'
        run: |
          az containerapp revision list --name hej-camping-app3 \
            --resource-group ${{ secrets.RESOURCE_GROUP }} --output json \
            | jq -r '.[0].name' \
            | xargs -I {} az containerapp revision set-mode --name hej-camping-app3 \
            --resource-group ${{ secrets.RESOURCE_GROUP }} --mode single \
            --revision {}
