name: Build and Push Docker Image to Azure Container Registry

on:
  push:
    branches:
      - CAM-35-Try-running-app-in-Azure-Container-Apps  # Specify the branch to trigger the workflow
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        
      # Login to Azure CLI using service principal credentials
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Log in to Azure Container Registry
      - name: 'Log in to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      # Build and push the Docker image to Azure Container Registry
      - name: 'Build and Push Docker Image'
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/hej-camping-app2:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/hej-camping-app2:${{ github.sha }}
